services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    ports:
      - '8123:8123'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeassistant:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 15s
    deploy:
      resources:
        limits:
          memory: 1G
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - NO_AUTOUPDATE
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      homeassistant:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  default:
